# Generated by Django 3.2.4 on 2021-06-22 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('wishes', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='productlandmark',
            name='landmark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.landmark'),
        ),
        migrations.AddField(
            model_name='productlandmark',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='landmarks',
            field=models.ManyToManyField(through='products.ProductLandmark', to='products.Landmark'),
        ),
        migrations.AddField(
            model_name='product',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.option'),
        ),
        migrations.AddField(
            model_name='product',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.region'),
        ),
        migrations.AddField(
            model_name='product',
            name='reviews',
            field=models.ManyToManyField(related_name='reviews_set', through='products.Review', to='users.User'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.subcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='wishes',
            field=models.ManyToManyField(related_name='wishes_set', through='wishes.Wish', to='users.User'),
        ),
        migrations.AddField(
            model_name='option',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.date'),
        ),
        migrations.AddField(
            model_name='landmark',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.region'),
        ),
        migrations.AddField(
            model_name='date',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
