# Generated by Django 3.2.4 on 2021-06-23 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210623_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='product',
        ),
        migrations.RemoveField(
            model_name='option',
            name='count',
        ),
        migrations.RemoveField(
            model_name='option',
            name='date',
        ),
        migrations.AddField(
            model_name='date',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='date',
            name='option',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.option'),
        ),
        migrations.AddField(
            model_name='option',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='productlandmark',
            table='product_landmarks',
        ),
    ]
