# Generated by Django 3.2.4 on 2021-06-25 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210623_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='creat_at',
            new_name='create_at',
        ),
    ]
